name: Test Fun JS Actions
on:
  push:
    branches: [main]
    paths: [test-js-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: node16
    steps:
      - name: Checkout
        uses: actions/checkout@v.3.3.0
      
      - name: Run my JS action
        id: hello-action
        uses: mmdolbow/gh-test-js-action@main

      - name: Output time set in the script
        run: echo "The time was set"
