name: Test Fun JS Actions
on:
  push:
    branches: [main]
    paths: [test-js-action/**]
  workflow_dispatch:

jobs:
  test-action:
    name: Mike GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Mike Test Local Action
        id: test-action
        uses: mmdolbow/gh-test-js-action@main
        with:
          milliseconds: 1000

      - name: Mike Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
