name: Test Super Exciting JS Actions
on:
  push:
    branches: [main]
    paths: [test-js-action/**]
  workflow_dispatch:

jobs:
  test-action:
    name: Pedestrian GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Mike Test Action in the JS Repo
        id: test-action
        uses: mmdolbow/gh-test-js-action@main
        with:
          milleseconds: 2000
          message: 'Positive Mental Attitude'

      - name: Mike Print Output
        id: output
        run: 
          echo "${{ steps.test-action.outputs.time }}"
          echo "${{ steps.test-action.outputs.outmessage }}"
